theme = "yukinord"

[editor]
color-modes = true
bufferline = "always"

[editor.statusline]
left = ["mode", "spacer", "version-control", "read-only-indicator", "file-name", "diagnostics", "workspace-diagnostics", "spinner"]
right = ["selections", "primary-selection-length", "position", "position-percentage", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
